config/routes.rb
Rails.application.routes.draw do
resources :users
resources :browse do
    get 'search', on: :collection
  end 
resources :books do
    get 'search', on: :collection
  end 

resources :sessions, only: [:new, :create]
delete '/signout', to: 'sessions#destroy'

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  scope :most_recent, -> { limit(10).order('author desc') }

  def self.search(q)
    where(['author LIKE ? OR title LIKE ?', "%#{q}%", "%#{q}%"])
  end

  def title=(value)
    super # does normal code for title=
    # TODO: only save a new book_cover_url, if title has changed
    self.book_cover_url = get_book_cover_url(self.title)
  end

  def get_book_cover_url(title)
    missing_cover_url = 'missing_cover.png'
    begin
      safe_title = URI::encode(title)
      my_key = ENV["goodreads_api"]
      book_url = "https://www.goodreads.com/search.xml?key=#{my_key}&q=#{safe_title}"

      search_results = HTTParty.get(book_url)

      book_data = search_results["GoodreadsResponse"]["search"]["results"]["work"][0]["best_book"]
      book_data.fetch("image_url", missing_cover_url)
    rescue NoMethodError => err # missing hash key
      Rails.logger.error err
      missing_cover_url
    end
  end


  # def review
  #   title = self.title.to_s.gsub(" ", "+")
  #   author = self.author.to_s.gsub(" ", "+")
  #   xml = "https://www.goodreads.com/book/title.xml?author=#{author}&key=lZx6I0xHirEZVRs8Xg2iPg&title=#{title}"
  #   # xml.map do |image|
  #   #   image.find(image_url)
  #   # end
  # end

  # def cover_photo
  #   title = self.title.to_s.gsub(" ", "+")
  #   xml = HTTParty.get("https://www.goodreads.com/search.xml?key=lZx6I0xHirEZVRs8Xg2iPg&q=#{title}")
  #   # xml.each do |image|
  #   #   xml.each do |x|
  #   #     xml.each do |y|
  #   #       xml.each do |m|
  #   #         image.find(:image_url)
  #   #       end
  #   #     end
  #   #   end
  #   # end
  #   xml["GoodreadsResponse"]["Request"][:search]["query"][:results]["work"][0][:image_url]
  #   # ["best_book type=\"Book\""]

  # end
end

app/models/browse.rb
class Browse <ActiveRecord::Base

  def self.search(q)
    where(['author LIKE ? OR title LIKE ?', "%#{q}%", "%#{q}%"])
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  #Add save handlers for formatting data
  before_create :create_remember_token
  before_save :normalize_fields
  # Validates name:
  validates :name,
    presence: true,
    length: {maximum: 50}

  # Validates email:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  #or use:   /[^@]+@[^@]+/

  # Validates password length
  validates :password,
    length: { minimum: 8 }

  # secure passwrd features
  has_secure_password


  # create a new remember token for the user:
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # creates a new session token for the user
  def create_remember_token
    remember_token = User.hash(User.new_remember_token)
  end
  #  normalize fields for consistancy
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  # require 'httparty'
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    # @books = Book.most_recent
    @books = current_user.books
    # @books.each do |book|
    #   cover(book.title)
    # end
    # get_book_cover(params[:title])
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def search
    @results = current_user.books.search(params[:q])
  end
  # <%= f.hidden_field :user_id, :value => current_user.id %>

  def browse
    @results = Book.search
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
      flash[:notice] = "Updated Book Successfully!"
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
      flash[:notice] = "Book added to shelf!"
    else
      render :new
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:notice] = "Book removed from shelf!"
  end

########################################################################
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :author, :user_id)
  end

end #end class BooksController

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def index
    @books = Book.all
    @display_books = Book.all
  end

  def show
    @books = Book.all
  end

  def search
    
    books = Book.all
    @results = books.search(params[:q])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :author, :user_id)
  end
end #End class

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action only: [:new, :create]

  def new #this is the sign in
    
  end

  def create
    # find user by their email
    user = User.find_by(email: params[:session][:email].downcase)

    # test if the user was found and authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to user
    else
      flash[:error] = "Invalid email/password. Please try again."
      redirect_to new_session_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# skip_before_action :require_signin, only: [:new, :create]
 
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      sign_in @user
      redirect_to @user #goes to user - show.html.erb
    else 
      render :new     #rails will look in views folder for new.html.erb
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to @user
      flash[:notice] = "Updated User Successfully!"
    else
      render :edit
    end
  end

  def destroy
  end


private

  def users_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # TODO write me!
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  def signed_in?
    current_user.present?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Managament methods
  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  # security checkpoint method
  def require_signin
    unless signed_in?
      store_location
      flash[:notice] = "Please Sign In"
      # redirect_to signin_url
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit 'Create Book', id: 'submit', class: "button expand" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="large-12 columns">
  <div class="fill-in-form"><h1>Editing book</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @book, class: "button expand"  %>
    <%= link_to 'Back', books_path, class: "button expand"  %>
  </div>
</div>

app/views/books/index.html.erb
<div id="browse-bg">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-4 small-12 columns">
        <img src="http://www.imran.com/xyper_images/icon-user-default.png" class="profile">
        <hr>
        <%= link_to 'Add A Book', new_book_path, class: "button expand"  %>
        <%= link_to 'Browse Libraries', browse_index_path, class: "button expand"  %>
        <%= form_tag(search_books_path, method: "get") do %>
          <%= label_tag(:q, "Search your shelf:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag "Search Your Shelf", :class => "button expand" %> 
        <% end %> 
      </div>
    <div class="large-8 small-12 columns" id="profile-shelf">
        <div class="row">
          <h3>My Shelf!</h3>
          <table>
            <thead>
              <tr>
                <th>Cover</th>
                <th>Title</th>
                <th>Author</th>
              </tr>
            </thead>
            <tbody>
              <% if @books.empty? %>
              <td class="nobooks">There's nothing on this shelf!</td>
              <% else %>
              <% @books.each do |book| %>
              <tr>
                <td class="cover"><%= image_tag book.book_cover_url, alt: book.title %></td>
                <td class="title"><%= book.title %></td>
                <td class="author"><%= book.author %></td>
                <td><%= link_to 'Show', book %></td>
                <td><%= link_to 'Edit', edit_book_path(book) %></td>
                <td class="notice"><%= link_to 'Remove', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="large-12 columns">
  <div class="fill-in-form">
    <h1>New Book</h1>

    <%= render 'form' %>

    <%= link_to 'Back', books_path, class: "button expand" %>
  </div>
</div>

app/views/books/search.html.erb
<div id="browse-bg">
  <div class="large-12 columns">
    <div class="row">
      <h1> Search Results </h1>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% if @results.empty? %>
            <td class="nobooks">No books to match your search!</td>
          <% else %>
          <% @results.each do |book| %>
            <tr>

              <td class="title"><%= book.title %></td>
              <td class="author"><%= book.author %></td>
              <td><%= link_to 'Show', book %></td>
              <td><%= link_to 'Edit', edit_book_path(book) %></td>
              <td class="notice"><%= link_to 'Remove', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Back', books_path, class: "button" %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="large-12 columns">
  <div class="fill-in-form">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>

    <p>
      <strong>Author:</strong>
      <%= @book.author %>
    </p>

    <p>
      <%= image_tag @book.book_cover_url %>
    </p>

    <%= link_to 'Edit', edit_book_path(@book), class: "button expand"  %>
    <%= link_to 'Back', books_path, class: "button expand"  %>

  </div>
</div>

app/views/browse/index.html.erb
<div id="browse-bg">
  <div class="large-12 columns">
    <div class="browse">
      <div class="row">
        <div class="large-4 medium-4 small-12 columns">
          <h3 class="browse-title">Browse all shelves </h3>
            <%= form_tag(search_browse_index_path, method: "get") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag "Search Shelves", :class => "button expand" %>
            <% end %>
            <%= link_to 'Welcome Page', root_path, class: "button expand" %>
        </div> <!-- end large 4 -->
        <div class="large-8 medium-8 small-12 columns">
          <div class="row">
            <h3 class="browse-title"> All Books Within <span class="purple">Shelf It</span></h3>
            <table>
              <thead>
                <tr>
                  <th>Cover</th>
                  <th>Title</th>
                  <th>Author</th>
                </tr>
              </thead>
              <tbody>
                <% if @books.empty? %>
                <td class="nobooks">There's nothing on this shelf!</td>
                <% else %>
                  <% @books.each do |book| %>
                    <tr>
                      <td class="cover"><%= image_tag book.book_cover_url, alt: book.title %></td>
                      <td id="title"><%= book.title %></td>
                      <td class="author"><%= book.author %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<footer class="row">
  <div class="large-12 columns"><hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright to Stacy Banks</p>
      </div> 
    </div>
  </div>
</footer>
</div>
</div>

app/views/browse/search.html.erb
<div id="browse-bg">
  <div class="large-12 columns">
    <div class="browse">
      <div class="row">
        <div class="large-4 medium-4 small-12 columns">
          <h3 class="browse-title">Browse all shelves </h3>
            <%= form_tag(search_browse_index_path, method: "get") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag "Search Shelves", :class => "button expand" %>
            <% end %>
            <%= link_to 'Welcome Page', root_path, class: "button expand" %>
            <%= link_to 'Browse Page', browse_index_path, class: "button expand" %>
          </div> <!-- end large 4 -->
        <div class="large-8 medium-8 small-12 columns">
          <div class="row">
            <h3 class="browse-title"> Search Results </h3>
            <table>
              <thead>
                <tr>
                  <th>Cover</th>
                  <th>Title</th>
                  <th>Author</th>
                </tr>
              </thead>
              <tbody>
                <% if @results.empty? %>
                  <td class="noresults">Sorry, no books by that title or author.</td>
                <% else %>
                  <% @results.each do |book| %>
                    <tr>
                      <td class="cover"><%= image_tag book.book_cover_url, alt: book.title %></td>
                      <td class="title"><%= book.title %></td>
                      <td class="author"><%= book.author %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_flash.html.erb
<li id="invalid">
  <% flash.each do |name, msg| %>
    <%= content_tag :p, msg, class: name %>
  <% end %>
</li>

app/views/common/_signout.html.erb
<% if signed_in? %>
    <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
      <span class="navigation-btn">Signed in as </span> <%= link_to current_user.name, current_user, class: "navigation-btn me" %>, <%= link_to 'View My Shelf', books_path, class: "navigation-btn view" %>
    <%= f.submit 'Sign Out', class: "button tiny signout" %>
    <% end %> 
  <% else %>
      <%= link_to 'Log In', new_session_path, class: "navigation-btn in" %>
      <%= link_to "Sign Up", new_user_path, class: "navigation-btn in" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Shelf It!" %></title>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
      <ul class="title-area">
        <li class="name">
          <h1 class="shelfit"><a href class="shelfit"><%= link_to 'Shelf It', root_path, class: "shelfit"%></a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <ul class="login">
              <%= render 'common/signout' %>
          </ul>
        </ul>
      </section>
    </nav>



    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="large-12 columns">
  <div class="fill-in-form">
    <h1>Edit <%= @user.name %>'s Profile</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1> Shelf it </h1>

app/views/users/new.html.erb
<div class="large-12 columns">
  <div class="fill-in-form">
    <h1>Sign up for <span class="purple">Shelf It</span> </h1>
    <h3>Your library away from home</h3>
    <% if @user.errors.any? %>
      <b> Errors:</b>
      <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %> </li>
          <% end %>
      </ul>
      <% end %> 

      <%= form_for @user do |f| %>
         <%= f.label :name %>
         <%= f.text_field :name %>

         <%= f.label :email %>
         <%= f.text_field :email %>

         <%= f.label :password %>
         <%= f.password_field :password %>

         <%= f.label :password_confirmation, 'Confirm Password' %>
         <%= f.password_field :password_confirmation %>

       <%= f.submit 'Submit', id: 'submit', class: "button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="browse-bg">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-4 small-12 columns">
        <img src="http://www.imran.com/xyper_images/icon-user-default.png" class="profile">
        <h3 id="profile-h3"><%= @user.name %></h3>
      </div><!-- end large 4 -->
      <div class="large-8 small-12 columns" id="profile-buttons">
        <%= link_to 'View My Shelf', books_path, class: "button expand" %>
        <%= link_to 'ProfileSettings', edit_user_path, class: "button expand" %>
        <%= link_to 'Browse Libraries', browse_index_path, class: "button expand" %>
        <br>
      </div><!-- end large 8 -->
    </div><!-- end row -->
  </div><!-- end large-12 -->
</div>

app/views/welcome/index.html.erb
<div class="background">
  <div class="intro">
    <div class="large-12 columns intro-pic ">
      <img class="intro-pic" src="http://i.imgur.com/EAbSLJH.jpg"/>
      <!-- <h1>Welcome to <span class="purple">Shelf It</span> </h1>
      <h3>Your library away from home</h3> -->
    </div>
  </div>

  <!-- Begin Books Thumbnails -->
  <div class="row">
    <div class="large-12 columns">
      <div class="row">
        <div class="large-4 medium-4 small-12 columns">
          <br>
          <br>
          <img class="bubbles" src="http://i.imgur.com/yx63i5O.jpg?1"/>
          <h3 class="bubble-text">Never forget what books you have at home</h3>
        </div>
        <div class="large-4 medium-4 small-12 columns">
          <br>
          <br>
          <img class="bubbles" src="http://i.imgur.com/S9V4ZjU.jpg"/>
          <h3 class="bubble-text">Log in and build your personal shelf</h3>
        </div>
        <div class="large-4 medium-4 small-12 columns">
          <br>
          <br>
          <img class="bubbles" src="http://i.imgur.com/maNiOIb.jpg"/>
          <h3 class="bubble-text">View your shelf on your phone</h3>
        </div>
      </div>  <!-- end row div -->
    </div>  <!-- end large-12 columns -->
  </div> <!-- end row div --> 
  <!-- end Books Thumbnails -->

  <div class="about">
    <div class="row">
      <div class="large-12 columns">
        <hr/>
          <p>Shelf It makes it easy to log the physical books you have at home, making your personal library accessible from anywhere! Simply sign up or log in to see your profile and your shelf. To add a book, just click 'Add a book' link, fill in the book's author and title, press submit, and Shelf It goes to work! We go to the Goodreads library and find your book. Once we've found it we add it to your shelf along with the book's cover!</p>
        <a href><%= link_to "Curious about other shelves? Browse all shelves!", browse_index_path, class: "button expand" %></a>
        <a id="goodreads" href="https://www.goodreads.com/" class="button expand">Find more books on Goodreads!</a>
        <!-- <a id="goodreads" href="https://www.goodreads.com/">Find more books on Goodreads!</a> -->
        <footer class="row">
          <div class="large-12 columns">
            <hr>
            <div class="row">
              <div class="large-6 columns">
                <p>© Copyright to Stacy Banks</p>
              </div> <!-- end large-6 -->
              <div class="large-6 columns">
                <ul class="inline-list right"></ul>
              </div><!-- end large-6 -->
            </div> <!-- end row -->
          </div> <!-- end large-12 -->
        </footer> <!-- end footer row -->
      </div>
      </div>
    </div>
  </div>
</div>